EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res32x4,shuv2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  IN_CHANNELS: [116, 232, 464, 1024]
  SHAPES: [1,4,8,16]
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 280
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

