EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res56,res20"
  PROJECT: "reviewkd_cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
REVIEWKD:
  REVIEWKD_WEIGHT: 0.6
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  SHAPES: [1, 8, 16, 32, 32]
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 280
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"