EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,wrn_40_2,wrn_16_2"
  PROJECT: "reviewkd_cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_16_2"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  IN_CHANNELS: [32, 64, 128, 128]
  OUT_CHANNELS: [32, 64, 128, 128]
  SHAPES: [1, 8, 16, 32]
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 280
  LR: 0.1
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"