EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res32x4,res8x4,cos_lr"
  PROJECT: "cifar100_baselines"
DATASET:
  NUM_WORKERS: 10
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  # FEATURE_SIZE: 
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

