EXPERIMENT:
  NAME: ""
  TAG: "reviewkd_RGA,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD_RGA"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  FEATURE_SIZE: [32, 16, 8, 4]
SOLVER:
  BATCH_SIZE: 128
  # EPOCHS: 240
  EPOCHS: 280
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

