EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,res110,res32,titanxp"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  SHAPES: [1, 8, 16, 32, 32]
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

