#ok
EXPERIMENT:
  NAME: ""
  TAG: "reviewkd_RGA,res32x4,shuv1"
  PROJECT: ""
DISTILLER:
  TYPE: "REVIEWKD_RGA"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV1"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  # IN_CHANNELS: [116, 232, 464, 1024]
  FEATURE_SIZE: [16, 8, 4, 4]
  IN_CHANNELS: [240, 480, 960, 960]
  SHAPES: [1, 4, 8, 16]
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 280
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

