EXPERIMENT:
  NAME: ""
  TAG: "reviewkd_RGA,vgg13,vgg8"
  PROJECT: ""
DISTILLER:
  TYPE: "REVIEWKD_RGA"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
REVIEWKD:
  REVIEWKD_WEIGHT: 8.0
  IN_CHANNELS: [128,256,512,512,512]
  OUT_CHANNELS: [128,256,512,512,512]
  OUT_SHAPES: [1, 4, 4, 8, 16]
  SHAPES: [1, 4, 4, 8, 16]
  FEATURE_SIZE: [16, 8, 4, 4, 1]
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 280
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
