EXPERIMENT:
  NAME: ""
  TAG: "REVIEWKD_RGA_decoupled,wrn_40_2,wrn_40_1"
  PROJECT: ""
DISTILLER:
  TYPE: "REVIEWKD_RGA_decoupled"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [32, 64, 128, 128]
  SHAPES: [1, 8, 16, 32]
  FEATURE_SIZE: [32, 16, 8, 1]
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 280
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 250]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"